version: "3.8"
services:
  mongo:
    image: mongo
    restart: always
    container_name: primer-mongo-d
    hostname: host-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ./dataMongo:/data/db
      - ./dataMongo/log:/var/log/mongodb
      